# Generated by Django 4.1 on 2024-07-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['dish_type'], 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
    ]
